version: '3.3'

services:
    perl:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: perl-5.26.2
                FROM_BASE: ${DOCKER_REGISTRY:-}base_container:${CONTAINER_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}base_container:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: perl
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: perl-5.26.${DOCKER_REGISTRY:-}2:${CONTAINER_TAG:-latest}
        labels:
            container.fingerprint: $CONTAINER_FINGERPRINT
            container.git.branch: $CONTAINER_GIT_BRANCH
            container.git.commit: $CONTAINER_GIT_COMMIT
            container.git.url: $CONTAINER_GIT_URL
            container.origin: $CONTAINER_ORIGIN
            container.original.name: perl
            container.version: ${CONTAINER_VERSION:-3.0.0}
